#!/usr/bin/env bash
# config to connect to server without a password
Host your_server
  HostName 54.158.216.6
  User ubuntu
  IdentityFile ~/.ssh/school
  PreferredAuthentications publickey
  PasswordAuthentication no
