#!/usr/bin/env bash
# 301 redirection task
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "301 Moved Permanently" > /var/www/html/index.nginx-debian.html'
sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.google.com permanent;" /etc/nginx/sites-available/default
service nginx start
