#!/usr/bin/env bash
# nginx server config
sudo apt-get update
sudo apt-get -y install nginx

# Create a custom Nginx configuration file
cat <<EOF | sudo tee /etc/nginx/sites-available/redirect.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    
    location /redirect_me {
        return 301 http://www.google.com;
    }
}
EOF

# Enable the custom configuration
sudo ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/


# Restart Nginx
if [ "$(pgrep -c nginx)" -le 0 ]; then
        sudo service nginx start
else
        sudo service nginx restart
fi
