#!/usr/bin/env bash
# installs nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "301 Redirection" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.google.com permanent;" /etc/nginx/sites-available/default
service nginx start
