#!/usr/bin/env bash
#while loop
i=1
while [ $i -ne 101 ]
do
	((three=i%3))
	((five=i%5))
	if [ $three -eq 0 ] && [ $five -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $three -eq 0 ] && [ $five -ne 0 ]; then 
		echo "Fizz"
	elif [ $five -eq 0 ] && [ $three -ne 0 ]; then
		echo "Buzz"
	else
		echo $i
	fi
	((i++))
done
