#!/usr/bin/env bash
#localhost and DNS
file_host=~/hosts.new
cp /etc/hosts $file_host

sed -i -e "$a\\n127.0.0.2\t127.0.0.1" $file_host
sed -i -e "$a\\n8.8.8.8\tfacebook.com\n" $file_host

cp -f $file_host /etc/hosts
