#!/usr/bin/env bash
# Get Apache to run on Docker container 
sudo apt-get update
sudo apt-get install -y apache2
sudo a2enmod rewrite
echo "Hello Holberton" | sudo tee /var/www/html/index.html
service apache2 start
